#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="$ROOT_DIR/terraform/environments/dev"
STAMP="$(date -u +"%Y%m%dT%H%M%SZ")"
OUT_DIR="${1:-$ROOT_DIR/docs/evidence/$STAMP}"
API_BASE_URL="${API_BASE_URL:-https://api.clearpathpropertygroup.com}"
CLEARPATH_API_KEY="${CLEARPATH_API_KEY:-}"

mkdir -p "$OUT_DIR"

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

capture() {
  local name="$1"
  shift

  {
    printf '$'
    printf ' %q' "$@"
    printf '\n\n'
    "$@"
  } >"$OUT_DIR/$name.txt" 2>&1 || {
    echo "Command failed while writing $OUT_DIR/$name.txt" >&2
    return 1
  }
}

tf_output() {
  terraform -chdir="$TF_DIR" output -raw "$1" 2>/dev/null || true
}

require_command aws
require_command terraform
require_command curl

ECS_CLUSTER="$(tf_output ecs_cluster_name)"
ECS_SERVICE="$(tf_output ecs_service_name)"
DB_INSTANCE_IDENTIFIER="$(tf_output db_instance_identifier)"
RDS_PROXY_NAME="$(tf_output rds_proxy_name)"
CLOUDFRONT_DISTRIBUTION_ID="$(tf_output cloudfront_distribution_id)"
CLOUDWATCH_DASHBOARD_NAME="$(tf_output cloudwatch_dashboard_name)"

capture terraform-outputs terraform -chdir="$TF_DIR" output
capture vpcs aws ec2 describe-vpcs --filters Name=tag:Project,Values=clearpath-api
capture subnets aws ec2 describe-subnets --filters Name=tag:Project,Values=clearpath-api
capture route-tables aws ec2 describe-route-tables --filters Name=tag:Project,Values=clearpath-api
capture security-groups aws ec2 describe-security-groups --filters Name=tag:Project,Values=clearpath-api
capture vpc-endpoints aws ec2 describe-vpc-endpoints --filters Name=tag:Project,Values=clearpath-api

if [[ -n "$ECS_CLUSTER" && -n "$ECS_SERVICE" ]]; then
  capture ecs-service aws ecs describe-services --cluster "$ECS_CLUSTER" --services "$ECS_SERVICE"
fi

if [[ -n "$DB_INSTANCE_IDENTIFIER" ]]; then
  capture rds-instance aws rds describe-db-instances --db-instance-identifier "$DB_INSTANCE_IDENTIFIER"
fi

if [[ -n "$RDS_PROXY_NAME" ]]; then
  capture rds-proxy aws rds describe-db-proxies --db-proxy-name "$RDS_PROXY_NAME"
  capture rds-proxy-targets aws rds describe-db-proxy-targets --db-proxy-name "$RDS_PROXY_NAME"
fi

if [[ -n "$CLOUDFRONT_DISTRIBUTION_ID" ]]; then
  capture cloudfront-distribution aws cloudfront get-distribution --id "$CLOUDFRONT_DISTRIBUTION_ID"
fi

if [[ -n "$CLOUDWATCH_DASHBOARD_NAME" ]]; then
  capture cloudwatch-dashboard aws cloudwatch get-dashboard --dashboard-name "$CLOUDWATCH_DASHBOARD_NAME"
fi

capture api-health curl -i -f "$API_BASE_URL/health"
capture api-ready curl -i -f "$API_BASE_URL/ready"
capture api-market curl -i -f "$API_BASE_URL/api/market/gwinnett"

if [[ -n "$CLEARPATH_API_KEY" ]]; then
  {
    printf '$ curl -i -f %q -H %q\n\n' "$API_BASE_URL/api/leads?county=Gwinnett&status=warm" "X-Clearpath-API-Key: <redacted>"
    curl -i -f "$API_BASE_URL/api/leads?county=Gwinnett&status=warm" -H "X-Clearpath-API-Key: $CLEARPATH_API_KEY"
  } >"$OUT_DIR/api-leads.txt" 2>&1
else
  echo "Skipping protected leads capture; set CLEARPATH_API_KEY to include it." >"$OUT_DIR/api-leads.txt"
fi

cat >"$OUT_DIR/README.md" <<EOF
# Deployment Evidence

- Captured at: $STAMP
- API base URL: $API_BASE_URL
- Terraform directory: $TF_DIR

These files are generated by \`scripts/collect-deployment-evidence.sh\` after an intentional AWS validation run.
EOF

echo "Deployment evidence written to $OUT_DIR"
