apiVersion: v1
kind: ConfigMap
metadata:
  name: clearpath-api-config
  namespace: clearpath-api
  labels:
    app.kubernetes.io/name: clearpath-api
    app.kubernetes.io/component: api
data:
  ENVIRONMENT: "kubernetes"
  AWS_REGION: "us-east-1"
  DB_NAME: "clearpath"
  DB_USER: "clearpath_app"
  DB_PROXY_ENDPOINT: ""
  DB_SECRET_ARN: ""
  GHL_WEBHOOK_SECRET: ""
  SKIP_DB_INIT: "false"
