apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: clearpath-api
  namespace: clearpath-api
  labels:
    app.kubernetes.io/name: clearpath-api
    app.kubernetes.io/component: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: clearpath-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
